model:
  target: dflat.metasurface.optical_model.NeuralCells
  ckpt_path: metasurface/ckpt/Nanocylinders_TiO2_U350H600/model.ckpt
  params:
    trainable_model: False
    param_bounds:
      - [15e-9, 160e-9]
      - [310e-9, 750e-9]
    nn_config:
      target: dflat.metasurface.nn_siren.SirenNet
      ckpt_path: None
      loss: torch.nn.MSELoss
      params:
        dim_in: 2
        dim_hidden: 256
        dim_out: 3
        num_layers: 2
        w0: 1.
        w0_initial: 30.
        use_bias: True
        dropout: 0

trainer:
  target: dflat.metasurface.trainer.Trainer_v1
  data: dflat.metasurface.datasets.Nanocylinders_TiO2_U350nm_H600nm
  ckpt_path: metasurface/ckpt/Nanocylinders_TiO2_U350H600/model.ckpt
  relative_ckpt: True
  params:
    test_split: 0.10
    learning_rate: .001
    epochs: 5000
    batch_size: 65536
    checkpoint_every_n: 100
    update_figure_every_epoch: True
    gradient_accumulation_steps: 1
    cosine_anneal_warm_restart: False
    cosine_anneal_minLR: .001
    cosine_anneal_T_0: 10
    cosine_anneal_T_mult: 3
