name: Pytest Workflow for DFlat
on: [push, pull_request]
jobs:
  run_unit_tests:
    name: Package Pytest Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install the package and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install torch 
          pip install .

      - name: Run pytest suite with coverage
        run: |
          pytest --cov=dflat --cov-report=xml tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: DeanHazineh/DFlat
